### ISSUE TITLE
Unable to load shared library 

### ISSUE THREAD

**Issue by Hamms** [izaakschroeder/node-graphicsmagick#1]
I'm not sure if this project is actively maintained, but it appears to be slightly broken:

I updated the path in test.js to point to build/Release rather than build/default, but then I get:

```
$ node test.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /foo/bar/node_modules/node-graphicsmagick/build/Release/GraphicsMagick.node
    at Object..node (module.js:463:11)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/foo/bar/node_modules/node-graphicsmagick/test.js:3:19)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
```

This seems quite similar to [this issue](https://github.com/Sannis/node-mysql-libmysqlclient/issues/107), in which the developer suggests the problem is related to the way Node is doing dynamic module loading in 0.6.x, but I can't find any other related documentation.

Any ideas?

**Comment by izaakschroeder** [comment]
Hey Hamms,

I am currently running node v0.5.11-pre. I will attempt to upgrade to a 0.6.x version of node and see if I can replicate the problem and get a patch or some information for you. What OS are you running, what version of GraphicsMagick, etc.?

Cheers,

**Comment by Hamms** [comment]
FreeBSD 8.2 and GraphicsMagick 1.3.12. Thanks!

Oh, and node 0.6.3

**Comment by izaakschroeder** [comment]
Hey Hamms,

I just upgraded to node.js 0.6.4 tonight and tested a clean build and it runs fine. Perhaps it is BSD related? I am running 64-bit Linux at the moment and have no BSD machine to test on. I imagine you followed the usual node-waf configure && node-waf? I am sending an updated test.js with the correct path in it now.

**Comment by Hamms** [comment]
I did indeed!

Please let me know if there's anything I can do to help you debug. If it helps, your node-magic project works just fine.

**Comment by izaakschroeder** [comment]
Hm. Perhaps if you also tried 0.6.4 or tried reinstalling GraphicsMagick? It seems weird that node-magic works and not this one. If that's the case I'm guessing it's GraphicsMagick related?

**Comment by Hamms** [comment]
I would tend to agree. I updated to 0.6.4 and reinstalled GraphicsMagick 1.3.12; still have the problem.

**Comment by izaakschroeder** [comment]
Interesting. I checked my version of GraphicsMagick and it is the same. Do you only have a BSD box or would it be possible to try on Linux also? I can try and get a BSD VM operational as well, though it might take a bit of time; what version of BSD are you running?

If it is related to dynamic module loading, it could also be that libmagic is being linked statically, and this one dynamically, though it seems weird it would do that. Will think more on this.

**Comment by Hamms** [comment]
I installed node 0.6.4 and GraphicsMagick 1.3.12 on my ubuntu box; exact same problem. I'm gonna install node v0.5.10 and see what happens.

**Comment by Hamms** [comment]
Okay, interesting. On node v0.5.10 I get `undefined symbol: XOpenDisplay`

**Comment by izaakschroeder** [comment]
Interesting; I wonder if either my node module or GraphicsMagick needs linking against libX? Might be worth seeing what `pkg-config GraphicsMagick --cflags --libs` does as that's how wscript decides what to link and include. Mine outputs only the following: `-I/usr/include/GraphicsMagick  -lGraphicsMagick`.

**Comment by Hamms** [comment]
I get `-I/usr/local/include/GraphicsMagick  -L/usr/local/lib -lGraphicsMagick`

**Comment by izaakschroeder** [comment]
If you run `objdump -T /usr/lib/libGraphicsMagick.so` do you find any references to libX? If it is still complaining about `XOpenDisplay` it might be worth just trying to force it to link against libX by putting `-lX` into the linker flags in the `wscript` file.

**Comment by Hamms** [comment]
Hmm, I don't actually have a `libGraphicsMagick.so`, just a `.a`

**Comment by izaakschroeder** [comment]
Oh how interesting; can you build it as a shared library (instead of just a static one)? Perhaps this is part of the reason? Although to be fair, you should still be able to check the ".a" file for references to the X library and then proceed as previously suggested.
